import {
  BuildingBlueprint,
  Decree,
  SectorState,
  CelestialBody,
} from "../types/simulation";
import { GenesisLorePayload } from "../types/genesis";

// ==========================================
// 1. PRESETS DES ENTITÉS
// ==========================================

export const PEOPLE_PRESETS: Record<string, {
  id: string;
  name: string;
  description: string;
  badge: string;
}> = {
  ASTRALIENS_SAPIENS: {
    id: "ASTRALIENS_SAPIENS",
    name: "Pionniers Astraliens Sapiens (Génération 1)",
    description: "Colonistes humains nés sur Terre dotés d'une grande adaptabilité culturelle et technologique.",
    badge: "Adaptabilité & Moral +15%",
  },
  CYBER_AUGMENTED: {
    id: "CYBER_AUGMENTED",
    name: "Pionniers Cybernétiques Augmentés",
    description: "Populations intégrées d'implants neuronaux et de prothèses sous-cutanées résistantes aux tempêtes.",
    badge: "Productivité Alliages +25%",
  },
  XENO_ADAPTED: {
    id: "XENO_ADAPTED",
    name: "Génération Xéno-Adaptée (G3)",
    description: "Humains génétiquement modifiés pour consommer moins d'O₂ et supporter de fortes gravités.",
    badge: "Consommation O₂ -20%",
  },
};

export const TERRITORY_PRESETS: Record<string, {
  id: string;
  name: string;
  description: string;
  badge: string;
}> = {
  MAILLAGE_ALPHA: {
    id: "MAILLAGE_ALPHA",
    name: "Maillage Hexagonal Concentrique Alpha",
    description: "Structure concentrique optimisée pour minimiser les distances de convoyage et les pertes énergétiques.",
    badge: "Efficacité Réseau +25%",
  },
  QUADRILLAGE_FORTIFIE: {
    id: "QUADRILLAGE_FORTIFIE",
    name: "Quadrillage Fortifié Bêta",
    description: "Zone de construction compartimentée avec sas de confinement en cas de dépression atmosphérique.",
    badge: "Résistance Structurelle +30%",
  },
  EXPANSION_LINEAIRE: {
    id: "EXPANSION_LINEAIRE",
    name: "Axe d'Expansion Linéaire Gamma",
    description: "Alignement axé sur la veine géothermique principale facilitant l'accès aux minerais rares.",
    badge: "Rendement Géothermique +35%",
  },
};

export const SHIP_PRESETS: Record<string, {
  id: string;
  name: string;
  description: string;
  badge: string;
}> = {
  ASTRA_NOVA_PRIME: {
    id: "ASTRA_NOVA_PRIME",
    name: "Astra-Nova Prime (Super-Vaisseau Amiral)",
    description: "Vaisseau d'exploration modulaire dote de processeurs quantiques et de ponts d'habitabilite avances.",
    badge: "Polyvalence & Module N.I.A. Optimise",
  },
  CHRONOS_HEAVY: {
    id: "CHRONOS_HEAVY",
    name: "Chronos-Heavy (Transporteur Blindé)",
    description: "Super-cuirassé industriel conçu pour acheminer de lourdes cargaisons minérales et des dômes renforcés.",
    badge: "Capacité Alliages +40% & Structure Renforcée",
  },
  PROMETHEE_BIO: {
    id: "PROMETHEE_BIO",
    name: "Prométhée-Bio (Arche de Bio-Ingénierie)",
    description: "Vaisseau-laboratoire équipé d'incubateurs génétiques et de dômes hydroponiques de secours.",
    badge: "Biomasse & Résilience Génétique +35%",
  },
};

export const STAR_SYSTEM_PRESETS: Record<string, {
  id: string;
  name: string;
  description: string;
  k_sol: number;
  ion_storm_interval_sols: number;
  r_cosmic: number;
  scan_energy_mod: number;
  badge: string;
  riskBadge: string;
  category: "BINARY" | "TRINARY" | "NEBULA" | "SINGULARITY" | "SOLAR";
}> = {
  ORION_SIGMA: {
    id: "ORION_SIGMA",
    name: "Binaire Pulsar Orion-Sigma",
    description: "Système hautement énergétique baigné de flux ioniques et de rayonnement gamma.",
    k_sol: 1.45,
    ion_storm_interval_sols: 4,
    r_cosmic: 78,
    scan_energy_mod: 1.3,
    badge: "Surtension Photovoltaïque +45%",
    riskBadge: "Orages Ioniques Fréquents",
    category: "BINARY",
  },
  CYGNUS_NULL: {
    id: "CYGNUS_NULL",
    name: "Nébuleuse Sombre Cygnus-Null",
    description: "Voile dense de poussière interstellaire réduisant l'énergie solaire mais riche en gaz rares.",
    k_sol: 0.35,
    ion_storm_interval_sols: 15,
    r_cosmic: 20,
    scan_energy_mod: 0.8,
    badge: "Collecte de Gaz +40%",
    riskBadge: "Pénombre Énergétique -65%",
    category: "NEBULA",
  },
  HELIOS_MAJOR: {
    id: "HELIOS_MAJOR",
    name: "Trinaire Rayonnant Helios-Major",
    description: "Trois soleils en résonance orbitale créant un climat chaud mais sujet à des éruptions massives.",
    k_sol: 2.1,
    ion_storm_interval_sols: 6,
    r_cosmic: 65,
    scan_energy_mod: 1.1,
    badge: "Énergie Solaire +110%",
    riskBadge: "Disjonctions Réseau 25%",
    category: "TRINARY",
  },
  TRAPPIST_7_PRIME: {
    id: "TRAPPIST_7_PRIME",
    name: "Système Nain TRAPPIST-7",
    description: "Système ultra-compact de 7 planètes telluriques gravitant autour d'une naine rouge froide.",
    k_sol: 0.75,
    ion_storm_interval_sols: 12,
    r_cosmic: 30,
    scan_energy_mod: 1.0,
    badge: "Stabilité Orbite & Portée Scanners +30%",
    riskBadge: "Éruptions UV Occasionnelles",
    category: "SOLAR",
  },
  BLACKHOLE_SINGULARITY_V: {
    id: "BLACKHOLE_SINGULARITY_V",
    name: "Horizon V - Trou Noir Gargantua",
    description: "Système limite bordant le disque d'accrétion d'un trou noir supermassif. Gravité quantique instable.",
    k_sol: 1.85,
    ion_storm_interval_sols: 3,
    r_cosmic: 95,
    scan_energy_mod: 1.6,
    badge: "Fluides Quantiques & Deutérium ×3",
    riskBadge: "Dilatation Temporelle & Radiations 95%",
    category: "SINGULARITY",
  },
  EPSILON_ERIDANI: {
    id: "EPSILON_ERIDANI",
    name: "Ceinture d'Astéroïdes Epsilon-Eridani",
    description: "Système jeune ceinturé d'essaims de comètes et de métaux rares en abondance libre.",
    k_sol: 1.15,
    ion_storm_interval_sols: 8,
    r_cosmic: 45,
    scan_energy_mod: 1.2,
    badge: "Gisements d'Alliages +60%",
    riskBadge: "Risque d'Impacts de Météorites",
    category: "SOLAR",
  },
};

export const PLANET_PRESETS: Record<string, {
  id: string;
  name: string;
  description: string;
  gravity_g: number;
  p_atm: number;
  m_metamorphic: number;
  w_ext: number;
  base_temp_c: number;
  badge: string;
  riskBadge: string;
  category: "TELLURIC" | "CRYO" | "DESERT" | "OCEAN" | "VOLCANIC" | "ASTEROID";
}> = {
  KAELIS_CRUST: {
    id: "KAELIS_CRUST",
    name: "Super-Terre Kaelis-Crust",
    description: "Monde tellurique dense aux filons de métaux lourds et à l'atmosphère corrosive.",
    gravity_g: 1.12,
    p_atm: 2.4,
    m_metamorphic: 1.35,
    w_ext: 1.3,
    base_temp_c: 12,
    badge: "Richesse Minérale +35%",
    riskBadge: "Corrosion & Gravité Forte",
    category: "TELLURIC",
  },
  EREBUS_GLACIES: {
    id: "EREBUS_GLACIES",
    name: "Monde Glacé Erebus-Glacies",
    description: "Planète cryogénique recouverte d'océans d'ammoniac et de banquises de glace pure.",
    gravity_g: 0.85,
    p_atm: 0.9,
    m_metamorphic: 0.8,
    w_ext: 2.0,
    base_temp_c: -140,
    badge: "Réserves d'Eau / Deutérium ×2",
    riskBadge: "Chauffage ×3.5 & Gel Conduites",
    category: "CRYO",
  },
  AURELIA_DESERTA: {
    id: "AURELIA_DESERTA",
    name: "Monde Aride Aurelia-Deserta",
    description: "Désert de silice infini balayé par des tempêtes abrasives qui encrassent les filtres.",
    gravity_g: 0.98,
    p_atm: 1.1,
    m_metamorphic: 1.5,
    w_ext: 1.2,
    base_temp_c: 45,
    badge: "Silice Abondante +50%",
    riskBadge: "Tempêtes Abrasives",
    category: "DESERT",
  },
  GLIESE_832C_OCEANIS: {
    id: "GLIESE_832C_OCEANIS",
    name: "Planète Océan Gliese-832c",
    description: "Monde aquatique géant avec archipels sous-marins et dômes flottants.",
    gravity_g: 1.05,
    p_atm: 1.8,
    m_metamorphic: 1.1,
    w_ext: 3.5,
    base_temp_c: 18,
    badge: "Abondance Eau / H₂O +100%",
    riskBadge: "Tempêtes Hydrodynamiques",
    category: "OCEAN",
  },
  TERRAN_NOVA_PRIME: {
    id: "TERRAN_NOVA_PRIME",
    name: "Terran Nova-Prime",
    description: "Super-Terre luxuriante aux conditions idéales, atmosphère oxygénée et sol fertile.",
    gravity_g: 1.0,
    p_atm: 1.0,
    m_metamorphic: 1.1,
    w_ext: 1.5,
    base_temp_c: 15,
    badge: "Habitabilité Optimale 98%",
    riskBadge: "Faune Xéno-Territoriale",
    category: "TELLURIC",
  },
  VULCAN_MAGMA_IX: {
    id: "VULCAN_MAGMA_IX",
    name: "Monde Magmatique Vulcain-IX",
    description: "Planète volcanique ultra-chaude traversée de rivières de basalte en fusion.",
    gravity_g: 1.35,
    p_atm: 3.2,
    m_metamorphic: 2.2,
    w_ext: 0.2,
    base_temp_c: 180,
    badge: "Énergie Géothermique ×4",
    riskBadge: "Chaleur Extrême & Éruptions",
    category: "VOLCANIC",
  },
  TITAN_METHAN_ALPHA: {
    id: "TITAN_METHAN_ALPHA",
    name: "Lune Cryo-Méthanier Titan-Alpha",
    description: "Astre froid recouvert de lacs d'hydrocarbures et d'atmosphère dense d'azote.",
    gravity_g: 0.65,
    p_atm: 1.4,
    m_metamorphic: 1.2,
    w_ext: 2.8,
    base_temp_c: -175,
    badge: "Synthèse Hydrocarbures +80%",
    riskBadge: "Froid Cryogénique Brutal",
    category: "CRYO",
  },
};

export const LEADER_ARCHETYPES = {
  TECHNOCRATE_CYBERNETIQUE: {
    id: "TECHNOCRATE_CYBERNETIQUE",
    name: "Gouverneur-Logos (Technocrate)",
    description: "Esprit cybernétique synchronisé avec la N.I.A., optimisant les rendements de calcul et de R&D.",
    q_leader: 110,
    fatigue_mod: 0.65,
    rd_bonus_pct: 15,
    humanitarian_mod: -20,
    badge: "Calcul N.I.A. +110 TFlops",
    category: "CYBER",
  },
  COMMANDANT_MARTIAL: {
    id: "COMMANDANT_MARTIAL",
    name: "Gouverneur-Imperium (Martial)",
    description: "Commandant d'acier maintenant l'ordre et le moral par la discipline et la puissance d'expédition.",
    q_leader: 40,
    fatigue_mod: 0.8,
    rd_bonus_pct: 0,
    humanitarian_mod: -10,
    badge: "Seuil d'Émeute Rehaussé à 85%",
    category: "MARTIAL",
  },
  DIPLOMATE_HUMANISTE: {
    id: "DIPLOMATE_HUMANISTE",
    name: "Gouverneur-Harmonia (Diplomate)",
    description: "Médiateur charismatique unissant les factions et assurant l'épanouissement des colons.",
    q_leader: 60,
    fatigue_mod: 0.9,
    rd_bonus_pct: 5,
    humanitarian_mod: 25,
    badge: "Approbation Éthique +40%",
    category: "DIPLOMAT",
  },
  XENOBIOLOGISTE_GENETICIEN: {
    id: "XENOBIOLOGISTE_GENETICIEN",
    name: "Gouverneur-Gaia (Xénobiologiste)",
    description: "Savant visionnaire combinant la génétique végétale et la résistance de la population.",
    q_leader: 75,
    fatigue_mod: 0.75,
    rd_bonus_pct: 20,
    humanitarian_mod: 15,
    badge: "Biomasse +35% & Santé +20%",
    category: "SCIENCE",
  },
  SCIENTIFIQUE_QUANTIQUE: {
    id: "SCIENTIFIQUE_QUANTIQUE",
    name: "Gouverneur-Helix (Physicien Quantique)",
    description: "Chercheur de pointe focalisé sur l'énergie du vide et l'accélération de la recherche.",
    q_leader: 130,
    fatigue_mod: 0.7,
    rd_bonus_pct: 30,
    humanitarian_mod: -5,
    badge: "Vitesse R&D +30%",
    category: "SCIENCE",
  },
};

// Modificateurs de jeu (Perks / Bonus & Flaws / Malus)
export const GAMEPLAY_BONUS_PRESETS = [
  {
    id: "SOLAR_GRID_OVERCLOCK",
    name: "Grille Solaire Surcadencée",
    costPoints: 1,
    badge: "+25% Production Énergie GW",
    description: "Cellules photovoltaïques supraconductrices à haut rendement.",
  },
  {
    id: "HYDROPONIC_HYPER_GENETICS",
    name: "Génétique Hydroponique Avancée",
    costPoints: 1,
    badge: "+30% Croissance Biomasse",
    description: "Souches végétales génétiquement modifiées pour dômes.",
  },
  {
    id: "QUANTUM_NEURAL_SYNAPSE",
    name: "Synapse Quantique N.I.A.",
    costPoints: 2,
    badge: "+150 TFlops & Construction Autonome",
    description: "Supercalculateur N.I.A. pré-synchronisé dès le Sol 1.",
  },
  {
    id: "REINFORCED_ALLOY_SHIELDS",
    name: "Boucliers Alliages Renforcés",
    costPoints: 1,
    badge: "+50% Intégrité Structurelle",
    description: "Coques et dômes en titane-carbone ultra-résistants.",
  },
  {
    id: "TITANIUM_CORE_DEPOSITS",
    name: "Filons de Titane Accessible",
    costPoints: 1,
    badge: "+40% Extraction Alliages",
    description: "Gisements de surface directement exploitables.",
  },
  {
    id: "DIPLOMATIC_HARMONY",
    name: "Charte de Concorde Initiale",
    costPoints: 1,
    badge: "+20% Approbation Factions",
    description: "Climat politique apaisé et décrets plus faciles à voter.",
  },
];

export const GAMEPLAY_MALUS_PRESETS = [
  {
    id: "VOLATILE_FUSION_CORES",
    name: "Cœurs de Fusion Instables",
    grantPoints: 1,
    badge: "Disjonctions Réseau 10%",
    description: "Micro-pannes électriques impromptues sur les dômes.",
  },
  {
    id: "ATMOSPHERIC_LEAKS",
    name: "Fuites Micro-Atmosphériques",
    grantPoints: 1,
    badge: "+15% Consommation Oxygène",
    description: "Joints d'étanchéité détériorés nécessitant plus d'O₂.",
  },
  {
    id: "SILICA_PNEUMOCONIOSIS",
    name: "Poussière Abrasive Infiltrante",
    grantPoints: 1,
    badge: "+20% Fatigue Gouverneur",
    description: "Filtres d'air à maintenance fréquente.",
  },
  {
    id: "CORROSIVE_ATMOSPHERE",
    name: "Atmosphère Acide Corrosive",
    grantPoints: 1,
    badge: "+20% Coût Maintenance Alliages",
    description: "Usure accélérée des infrastructures extérieures.",
  },
  {
    id: "FACTIONAL_DISCORD",
    name: "Rivalités Factionnelles Ancrées",
    grantPoints: 2,
    badge: "-15% Stabilité Initiale",
    description: "Factions en tension permanente exigeant des compromis.",
  },
];

// ==========================================
// 2. LES 12 ÈRES ET 12 SOUS-ÈRES DU JEU (144 NIVEAUX)
// ==========================================

export const ERAS_CONFIG = [
  {
    era: "ERE_1_PIONNIER",
    order: 1,
    name: "1. Édaffage & Survie Pionnière",
    subtitle: "Survie Initiale & Déploiement d'Urgence",
    unlockedBuildings: ["MODULE_ATTERRISSAGE", "EPURATEUR_URGENCE", "SERRES_URGENCE"],
    unlockCondition: "Réveiller 1 000 colons et survivre 5 Sols.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 1.${i + 1} : Palier Operatif ${i + 1}`,
      bonusDesc: `+${i * 1.5}% Vitesse Construction · +${i * 20} TFlops NIA`,
    })),
  },
  {
    era: "ERE_2_VILLAGE",
    order: 2,
    name: "2. Bourgade & Serres Dôme",
    subtitle: "Établissement du Dôme Alpha",
    unlockedBuildings: ["DOME_RESIDENTIEL_P1", "FOREUSE_SURFACE", "STATION_POMPAGE_GLACE"],
    unlockCondition: "Stabilité > 60% et réserves de biomasse > 10 000 kg.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 2.${i + 1} : Expansion Dôme Alpha ${i + 1}`,
      bonusDesc: `+${(i + 1) * 2}% Rendement Biomasse · +${(i + 1) * 25} TFlops`,
    })),
  },
  {
    era: "ERE_3_COLONIE",
    order: 3,
    name: "3. Colonie Autosuffisante",
    subtitle: "Réseau Hydraulique & Conseil Municipal",
    unlockedBuildings: ["DISPENSAIRE_MEDICAL", "ATELIER_RECYCLAGE", "CENTRALE_PHOTOVOLTAIQUE"],
    unlockCondition: "Population > 3 000 et 3 bâtiments construits.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 3.${i + 1} : Autonomie Énergétique ${i + 1}`,
      bonusDesc: `+${(i + 1) * 1.5}% Production Électricité · Stabilité +${Math.round((i + 1) * 0.5)}%`,
    })),
  },
  {
    era: "ERE_4_METROPOLE",
    order: 4,
    name: "4. Métropole Industrielle",
    subtitle: "Ligne Maglev & Fonderie d'Alliages",
    unlockedBuildings: ["HOPITAL_CENTRALISE", "FONDERIE_TITANE", "RESEAU_MAGLEV"],
    unlockCondition: "Population > 10 000 et décret industriel voté.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 4.${i + 1} : Métallurgie Avancée ${i + 1}`,
      bonusDesc: `+${(i + 1) * 2}% Extraction Alliages · +${(i + 1) * 30} TFlops`,
    })),
  },
  {
    era: "ERE_5_TERRAFORMATION",
    order: 5,
    name: "5. Injecteurs & Climat Z+1",
    subtitle: "Ouverture de la Surface Z+1 et Pression O₂",
    unlockedBuildings: ["UNIVERSITE_RECHERCHE", "SUPERCALCULATEUR_NIA", "CENTRALE_FUSION"],
    unlockCondition: "Population > 25 000 et niveau de Leader ≥ 3.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 5.${i + 1} : Injection Atmosphérique ${i + 1}`,
      bonusDesc: `Pression Atmosphérique +${((i + 1) * 0.03).toFixed(2)} atm · Biomasse Z+1 +${(i + 1) * 3}%`,
    })),
  },
  {
    era: "ERE_6_INDUSTRIELLE",
    order: 6,
    name: "6. Super-Complexe Métallurgique",
    subtitle: "Raffinerie Deutérium & Mines Profondes Z-1",
    unlockedBuildings: ["PREFECTURE", "RAFFINERIE_DEUTERIUM", "CENTRE_LOGISTIQUE"],
    unlockCondition: "Stabilité > 75% et réserves d'énergie > 500 GW.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 6.${i + 1} : Mine Profonde Z-1 ${i + 1}`,
      bonusDesc: `+${(i + 1) * 4}% Deutérium · Vitesse Auto-Chantier NIA +${(i + 1) * 2}%`,
    })),
  },
  {
    era: "ERE_7_ORBITALE",
    order: 7,
    name: "7. Ring Orbital & Ascenseur Z+2",
    subtitle: "Infrastructures Spatiales et Station d'Altitude",
    unlockedBuildings: ["ASSEMBLEE_REGIONALE", "BARRAGE_GEOTHERMIQUE", "USINE_IMPRESSION_3D"],
    unlockCondition: "Population > 60 000 et accord de faction unanime.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 7.${i + 1} : Ring Orbital Z+2 ${i + 1}`,
      bonusDesc: `Puissance Orbitale +${(i + 1) * 5} MW · Portée Scanners +${(i + 1) * 4}%`,
    })),
  },
  {
    era: "ERE_8_RESEAU_PLANETAIRE",
    order: 8,
    name: "8. Réseau Métropolitain Global",
    subtitle: "Ascenseur Spatial & Interconnexions Dômes",
    unlockedBuildings: ["MINISTERE_DEFENSE", "ASCENSEUR_SPATIAL", "CENTRE_TERRAFORMAGE"],
    unlockCondition: "Gouvernance Niveau 5 et Maître-Gouverneur.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 8.${i + 1} : Maillage Supraconducteur ${i + 1}`,
      bonusDesc: `Efficacité Logistique Réseau +${(i + 1) * 1.5}%`,
    })),
  },
  {
    era: "ERE_9_QUANTIQUE",
    order: 9,
    name: "9. Matrice Quantique & Hyper-N.I.A.",
    subtitle: "Matrice Planétaire & Super-Calculateur Quantum",
    unlockedBuildings: ["MATRICE_RESEAU_CONTINENTALE", "DOME_CONCORDE"],
    unlockCondition: "Traités de paix avec tous les Gouverneurs rivaux.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 9.${i + 1} : Processeur Quantique K-900 ${i + 1}`,
      bonusDesc: `Processeur Quantum +${(i + 1) * 100} TFlops · Auto-Construction Instantanée 5%`,
    })),
  },
  {
    era: "ERE_10_STELLAIRE",
    order: 10,
    name: "10. Exploitation Stellaire 4X",
    subtitle: "Flottes d'Exploration & Extraction Astéroïdale",
    unlockedBuildings: ["SPHERE_ECOLOGIQUE", "PORTAIL_SAUTS_XENO"],
    unlockCondition: "Terraformation à 100% et Ring Orbital achevé.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 10.${i + 1} : Flotte Stellaire ${i + 1}`,
      bonusDesc: `Rendement Minage 4X +${(i + 1) * 5}% · Vitesse Vaisseaux +${(i + 1) * 3}%`,
    })),
  },
  {
    era: "ERE_11_ASCENSION",
    order: 11,
    name: "11. Cité Céleste & Bio-Cybernétique",
    subtitle: "Harmonie Transhumaine & Biosphère Intégrale",
    unlockedBuildings: ["SPHERE_ECOLOGIQUE", "PORTAIL_SAUTS_XENO"],
    unlockCondition: "Ascension Bio-Cybernétique & Approbation 90%.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 11.${i + 1} : Harmonie Transhumaine ${i + 1}`,
      bonusDesc: `Espérance de Vie Colons +${(i + 1) * 5} Sols · Stress -${(i + 1) * 2}%`,
    })),
  },
  {
    era: "ERE_12_SINGULARITE",
    order: 12,
    name: "12. Archipel Omniscient & Singularité",
    subtitle: "Utopie Cosmique Absolue & Maîtrise Multivers",
    unlockedBuildings: ["PORTAIL_SAUTS_XENO"],
    unlockCondition: "Événement d'Ascension Oméga complété.",
    subEras: Array.from({ length: 12 }, (_, i) => ({
      subEraOrder: i + 1,
      name: `Sous-Ère 12.${i + 1} : Singularité Omnisciente ${i + 1}`,
      bonusDesc: `Multiplicateur Toutes Ressources ×${(1 + (i + 1) * 0.1).toFixed(1)}`,
    })),
  },
];

// ==========================================
// 3. LES 16 SECTEURS DE L'ARCHE
// ==========================================

export const INITIAL_SECTORS: SectorState[] = [
  {
    id: "SEC-01",
    code: "SEC-01",
    name: "Réacteur Principal Alpha",
    categoryGroup: "PROPULSION",
    techLevel: 1,
    personnelAssigned: 120,
    integrityPct: 100,
    maintenanceStatusPct: 95,
    temperatureC: 85,
    radiationLevel: 12,
    isOnline: true,
    connectedSectors: ["SEC-02", "SEC-03", "SEC-04"],
    resourcesStored: { deuterium_kg: 50, energy_gw: 120 },
    storageCapacity: 200,
    description: "Cœur de fusion Deutérium-Tritium alimentant la poussée principale.",
  },
  {
    id: "SEC-02",
    code: "SEC-02",
    name: "Réacteur Secondaire Bêta",
    categoryGroup: "PROPULSION",
    techLevel: 1,
    personnelAssigned: 80,
    integrityPct: 98,
    maintenanceStatusPct: 92,
    temperatureC: 72,
    radiationLevel: 8,
    isOnline: true,
    connectedSectors: ["SEC-01", "SEC-04"],
    resourcesStored: { deuterium_kg: 30, energy_gw: 80 },
    storageCapacity: 150,
    description: "Unité de fusion catalysée de secours et d'appoint.",
  },
  {
    id: "SEC-03",
    code: "SEC-03",
    name: "Refroidissement Primaire",
    categoryGroup: "PROPULSION",
    techLevel: 1,
    personnelAssigned: 60,
    integrityPct: 100,
    maintenanceStatusPct: 98,
    temperatureC: 15,
    radiationLevel: 2,
    isOnline: true,
    connectedSectors: ["SEC-01", "SEC-04"],
    resourcesStored: { water_l: 5000 },
    storageCapacity: 10000,
    description: "Boucles thermiques cryogéniques régulant la chaleur des réacteurs.",
  },
  {
    id: "SEC-04",
    code: "SEC-04",
    name: "Contrôle Réaction & Sûreté",
    categoryGroup: "PROPULSION",
    techLevel: 1,
    personnelAssigned: 45,
    integrityPct: 100,
    maintenanceStatusPct: 99,
    temperatureC: 22,
    radiationLevel: 1,
    isOnline: true,
    connectedSectors: ["SEC-01", "SEC-02", "SEC-03", "SEC-16"],
    resourcesStored: {},
    storageCapacity: 50,
    description: "Sas de confinement magnétique et disjoncteurs quantiques.",
  },
  {
    id: "SEC-05",
    code: "SEC-05",
    name: "Dôme Agro-Alimentaire Alpha",
    categoryGroup: "SUPPORT_VIE",
    techLevel: 1,
    personnelAssigned: 200,
    integrityPct: 100,
    maintenanceStatusPct: 90,
    temperatureC: 24,
    radiationLevel: 0,
    isOnline: true,
    connectedSectors: ["SEC-06", "SEC-07", "SEC-08"],
    resourcesStored: { biomass_kg: 2500 },
    storageCapacity: 8000,
    description: "Cultures hydroponiques automatisées et spiruline haute densité.",
  },
  {
    id: "SEC-06",
    code: "SEC-06",
    name: "Dôme O₂ & Recyclage CO₂",
    categoryGroup: "SUPPORT_VIE",
    techLevel: 1,
    personnelAssigned: 90,
    integrityPct: 100,
    maintenanceStatusPct: 94,
    temperatureC: 20,
    radiationLevel: 0,
    isOnline: true,
    connectedSectors: ["SEC-05", "SEC-08", "SEC-09"],
    resourcesStored: { oxygen_l: 15000 },
    storageCapacity: 50000,
    description: "Électrolyseurs massifs et bioréacteurs à micro-algues fixatrices.",
  },
  {
    id: "SEC-07",
    code: "SEC-07",
    name: "Serres Expérimentales",
    categoryGroup: "SUPPORT_VIE",
    techLevel: 1,
    personnelAssigned: 75,
    integrityPct: 95,
    maintenanceStatusPct: 88,
    temperatureC: 26,
    radiationLevel: 0,
    isOnline: true,
    connectedSectors: ["SEC-05", "SEC-08"],
    resourcesStored: { biomass_kg: 800 },
    storageCapacity: 3000,
    description: "Laboratoire d'hybridation pour espèces végétales adaptées au régolithe.",
  },
  {
    id: "SEC-08",
    code: "SEC-08",
    name: "Réserves d'Eau & Purification",
    categoryGroup: "SUPPORT_VIE",
    techLevel: 1,
    personnelAssigned: 60,
    integrityPct: 100,
    maintenanceStatusPct: 96,
    temperatureC: 18,
    radiationLevel: 0,
    isOnline: true,
    connectedSectors: ["SEC-05", "SEC-06", "SEC-07", "SEC-10"],
    resourcesStored: { water_l: 25000 },
    storageCapacity: 60000,
    description: "Osmose inverse et réservoirs souterrains de haute pureté.",
  },
  {
    id: "SEC-09",
    code: "SEC-09",
    name: "Quartiers Résidentiels Alpha",
    categoryGroup: "RESIDENTIEL",
    techLevel: 1,
    personnelAssigned: 150,
    integrityPct: 100,
    maintenanceStatusPct: 91,
    temperatureC: 21,
    radiationLevel: 0,
    isOnline: true,
    connectedSectors: ["SEC-06", "SEC-10", "SEC-11"],
    resourcesStored: {},
    storageCapacity: 100,
    description: "Habitations pressurisées modulaires pour les pionniers actifs.",
  },
  {
    id: "SEC-10",
    code: "SEC-10",
    name: "Quartiers Résidentiels Bêta",
    categoryGroup: "RESIDENTIEL",
    techLevel: 1,
    personnelAssigned: 110,
    integrityPct: 97,
    maintenanceStatusPct: 89,
    temperatureC: 21,
    radiationLevel: 0,
    isOnline: true,
    connectedSectors: ["SEC-08", "SEC-09", "SEC-12"],
    resourcesStored: {},
    storageCapacity: 100,
    description: "Logements optimisés pour les corps de spécialistes et ingénieurs.",
  },
  {
    id: "SEC-11",
    code: "SEC-11",
    name: "Caissons Cryogéniques",
    categoryGroup: "RESIDENTIEL",
    techLevel: 1,
    personnelAssigned: 50,
    integrityPct: 100,
    maintenanceStatusPct: 99,
    temperatureC: -180,
    radiationLevel: 1,
    isOnline: true,
    connectedSectors: ["SEC-09", "SEC-12"],
    resourcesStored: {},
    storageCapacity: 500,
    description: "Voûte de stase cryogénique abritant les colons en sommeil profond.",
  },
  {
    id: "SEC-12",
    code: "SEC-12",
    name: "Centre Médical & Recherche",
    categoryGroup: "RESIDENTIEL",
    techLevel: 1,
    personnelAssigned: 85,
    integrityPct: 100,
    maintenanceStatusPct: 97,
    temperatureC: 22,
    radiationLevel: 0,
    isOnline: true,
    connectedSectors: ["SEC-10", "SEC-11", "SEC-16"],
    resourcesStored: {},
    storageCapacity: 200,
    description: "Dispensaire avancé, nanothérapie et soins chirurgicaux du Leader.",
  },
  {
    id: "SEC-13",
    code: "SEC-13",
    name: "Ateliers Fabrication Lourds",
    categoryGroup: "FABRICATION_DEFENSE",
    techLevel: 1,
    personnelAssigned: 180,
    integrityPct: 100,
    maintenanceStatusPct: 92,
    temperatureC: 38,
    radiationLevel: 4,
    isOnline: true,
    connectedSectors: ["SEC-14", "SEC-15"],
    resourcesStored: { alloys_tonnes: 35 },
    storageCapacity: 300,
    description: "Imprimantes 3D métalliques et fonderies de composites de titane.",
  },
  {
    id: "SEC-14",
    code: "SEC-14",
    name: "Hangar à Sondes & Véhicules",
    categoryGroup: "FABRICATION_DEFENSE",
    techLevel: 1,
    personnelAssigned: 95,
    integrityPct: 96,
    maintenanceStatusPct: 90,
    temperatureC: 16,
    radiationLevel: 3,
    isOnline: true,
    connectedSectors: ["SEC-13", "SEC-15"],
    resourcesStored: {},
    storageCapacity: 150,
    description: "Aire d'entretien des rovers de surface et des navettes d'exploration.",
  },
  {
    id: "SEC-15",
    code: "SEC-15",
    name: "Blindage & Défense Orbitale",
    categoryGroup: "FABRICATION_DEFENSE",
    techLevel: 1,
    personnelAssigned: 70,
    integrityPct: 100,
    maintenanceStatusPct: 98,
    temperatureC: 10,
    radiationLevel: 15,
    isOnline: true,
    connectedSectors: ["SEC-13", "SEC-14", "SEC-16"],
    resourcesStored: {},
    storageCapacity: 100,
    description: "Émetteurs de bouclier magnétique et tourelles d'interception cinétique.",
  },
  {
    id: "SEC-16",
    code: "SEC-16",
    name: "Centre de Commande Secondaire",
    categoryGroup: "FABRICATION_DEFENSE",
    techLevel: 1,
    personnelAssigned: 50,
    integrityPct: 100,
    maintenanceStatusPct: 100,
    temperatureC: 20,
    radiationLevel: 0,
    isOnline: true,
    connectedSectors: ["SEC-04", "SEC-12", "SEC-15"],
    resourcesStored: {},
    storageCapacity: 100,
    description: "Bunker N.I.A. de secours et réplication d'état en temps réel.",
  },
];

// ==========================================
// 4. LES 12 DOMAINES RÉGALIENS
// ==========================================

export const REGALIAN_DOMAINS = [
  { id: 1, name: "Habitat", zone: "Zone 1", desc: "Force de travail & cohésion résidentielle", icon: "Home" },
  { id: 2, name: "Santé", zone: "Zone 1", desc: "Gestion des infections xénologiques & O2 médical", icon: "Activity" },
  { id: 3, name: "Éducation", zone: "Zone 1", desc: "Qualification des Astraliens & points R&D", icon: "GraduationCap" },
  { id: 4, name: "Culture", zone: "Zone 1", desc: "Popularité du Leader & régulation du stress", icon: "Heart" },
  { id: 5, name: "Agriculture", zone: "Zone 1", desc: "Biomasse protéique & recyclage des eaux", icon: "Leaf" },
  { id: 6, name: "Cyberespace", zone: "Zone 1", desc: "Bande passante N.I.A. & calcul quantique", icon: "Cpu" },
  { id: 7, name: "Énergie", zone: "Zone 3", desc: "Photovoltaïque, géothermie & réacteurs à fusion", icon: "Zap" },
  { id: 8, name: "Industrie", zone: "Zone 3", desc: "Métallurgie des alliages & cristaux supraconducteurs", icon: "Hammer" },
  { id: 9, name: "Protection Civile", zone: "Zone 3", desc: "Boucliers hermétiques & brigades d'avarie", icon: "Shield" },
  { id: 10, name: "Transports", zone: "Zone 3", desc: "Maglev sous vide & convois logistiques inter-dômes", icon: "Truck" },
  { id: 11, name: "Écologie", zone: "Zone 2/3", desc: "Génie climatique & capture des poussières toxiques", icon: "Wind" },
  { id: 12, name: "Sécurité Extérieure", zone: "Zone 3/4", desc: "Défense orbitale & scans d'exploration 4X", icon: "Crosshair" },
];

// ==========================================
// 5. BLUEPRINTS DES BÂTIMENTS
// ==========================================

export const BUILDING_BLUEPRINTS: Record<string, BuildingBlueprint> = {
  MODULE_ATTERRISSAGE: {
    blueprint_id: "MODULE_ATTERRISSAGE",
    name: "Module d'Atterrissage de Secours",
    category: "HAB",
    unlocked_era: 1,
    min_leader_level: 1,
    min_governance_level: 1,
    allowed_z_levels: ["Z_PLUS_1_SURFACE", "Z_ZERO_DOME"],
    allowed_zones: ["ZONE_1_DOME_CORE", "ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 3, height: 3 },
    base_inputs: { energy_gw: 5, oxygen_l: 100 },
    base_outputs: { housing_capacity: 100, storage_alloys: 50 },
    construction_cost: { alloys_tonnes: 10, energy_gw: 10 },
    maintenance_cost_alloys: 0.5,
    description: "Structure pressurisée d'urgence servant de quartier général temporaire.",
  },
  EPURATEUR_URGENCE: {
    blueprint_id: "EPURATEUR_URGENCE",
    name: "Épurateur d'Air d'Urgence",
    category: "ENE",
    unlocked_era: 1,
    min_leader_level: 1,
    min_governance_level: 1,
    allowed_z_levels: ["Z_ZERO_DOME"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 2, height: 2 },
    base_inputs: { energy_gw: 15 },
    base_outputs: { oxygen_l: 500 },
    construction_cost: { alloys_tonnes: 8, energy_gw: 5 },
    maintenance_cost_alloys: 0.8,
    description: "Système mobile de filtration et recyclage d'oxygène.",
  },
  SERRES_URGENCE: {
    blueprint_id: "SERRES_URGENCE",
    name: "Serres de Secours sous Bâche",
    category: "AGR",
    unlocked_era: 1,
    min_leader_level: 1,
    min_governance_level: 1,
    allowed_z_levels: ["Z_ZERO_DOME"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 2, height: 2 },
    base_inputs: { water_l: 80, energy_gw: 10 },
    base_outputs: { biomass_kg: 150 },
    construction_cost: { alloys_tonnes: 5, water_l: 200 },
    maintenance_cost_alloys: 0.4,
    description: "Cultures sous polymères ultra-résistants fournissant des nutriments vitaux.",
  },
  DOME_RESIDENTIEL_P1: {
    blueprint_id: "DOME_RESIDENTIEL_P1",
    name: "Dôme Résidentiel Primaire",
    category: "HAB",
    unlocked_era: 2,
    min_leader_level: 1,
    min_governance_level: 1,
    allowed_z_levels: ["Z_ZERO_DOME"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 3, height: 3 },
    base_inputs: { oxygen_l: 250, water_l: 300, energy_gw: 20 },
    base_outputs: { housing_capacity: 450, social_cohesion: 10 },
    construction_cost: { alloys_tonnes: 30, energy_gw: 25 },
    maintenance_cost_alloys: 1.5,
    description: "Arcologie de vie pérenne avec isolation acoustique et sas sécurisés.",
  },
  FOREUSE_SURFACE: {
    blueprint_id: "FOREUSE_SURFACE",
    name: "Foreuse Automatisée de Surface",
    category: "IND",
    unlocked_era: 2,
    min_leader_level: 1,
    min_governance_level: 1,
    allowed_z_levels: ["Z_PLUS_1_SURFACE"],
    allowed_zones: ["ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 2, height: 2 },
    base_inputs: { energy_gw: 35 },
    base_outputs: { alloys_tonnes: 8, silica_raw: 20 },
    construction_cost: { alloys_tonnes: 25, energy_gw: 15 },
    maintenance_cost_alloys: 2.0,
    description: "Excavateur robotisé extrayant le régolithe et les filons métamorphiques.",
  },
  STATION_POMPAGE_GLACE: {
    blueprint_id: "STATION_POMPAGE_GLACE",
    name: "Station de Pompage de Glace",
    category: "ENE",
    unlocked_era: 2,
    min_leader_level: 1,
    min_governance_level: 1,
    allowed_z_levels: ["Z_PLUS_1_SURFACE", "Z_MINUS_1_SUB"],
    allowed_zones: ["ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 2, height: 2 },
    base_inputs: { energy_gw: 25 },
    base_outputs: { water_l: 800, deuterium_kg: 3 },
    construction_cost: { alloys_tonnes: 20, energy_gw: 20 },
    maintenance_cost_alloys: 1.2,
    description: "Sonde thermique sous-terraine forant les poches de pergélisol.",
  },
  DISPENSAIRE_MEDICAL: {
    blueprint_id: "DISPENSAIRE_MEDICAL",
    name: "Dispensaire Médical & Bio-Soins",
    category: "HAB",
    unlocked_era: 3,
    min_leader_level: 2,
    min_governance_level: 2,
    allowed_z_levels: ["Z_ZERO_DOME"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 2, height: 2 },
    base_inputs: { energy_gw: 15, oxygen_l: 100 },
    base_outputs: { health_recovery_rate: 15 },
    construction_cost: { alloys_tonnes: 20, energy_gw: 20 },
    maintenance_cost_alloys: 1.0,
    description: "Centre de décontamination des poussières de silice et soins intensifs.",
  },
  ATELIER_RECYCLAGE: {
    blueprint_id: "ATELIER_RECYCLAGE",
    name: "Atelier de Recyclage Moléculaire",
    category: "IND",
    unlocked_era: 3,
    min_leader_level: 2,
    min_governance_level: 2,
    allowed_z_levels: ["Z_ZERO_DOME", "Z_MINUS_1_SUB"],
    allowed_zones: ["ZONE_1_DOME_CORE", "ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 2, height: 2 },
    base_inputs: { energy_gw: 20 },
    base_outputs: { alloys_tonnes: 5, waste_reduction_pct: 30 },
    construction_cost: { alloys_tonnes: 15, energy_gw: 10 },
    maintenance_cost_alloys: 0.8,
    description: "Reconditionne les débris métalliques et les filtres encrassés.",
  },
  CENTRALE_PHOTOVOLTAIQUE: {
    blueprint_id: "CENTRALE_PHOTOVOLTAIQUE",
    name: "Centrale Photovoltaïque Haute-Radiance",
    category: "ENE",
    unlocked_era: 3,
    min_leader_level: 2,
    min_governance_level: 2,
    allowed_z_levels: ["Z_PLUS_1_SURFACE"],
    allowed_zones: ["ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 3, height: 3 },
    base_inputs: {},
    base_outputs: { energy_gw: 80 },
    construction_cost: { alloys_tonnes: 35, energy_gw: 5 },
    maintenance_cost_alloys: 1.5,
    description: "Panneaux quartz à orientation quantique captant la radiance stellaire.",
  },
  CENTRALE_FUSION: {
    blueprint_id: "CENTRALE_FUSION",
    name: "Réacteur à Fusion Profond",
    category: "ENE",
    unlocked_era: 5,
    min_leader_level: 3,
    min_governance_level: 3,
    allowed_z_levels: ["Z_MINUS_2_DEEP"],
    allowed_zones: ["ZONE_1_DOME_CORE", "ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 4, height: 4 },
    base_inputs: { deuterium_kg: 10 },
    base_outputs: { energy_gw: 350 },
    construction_cost: { alloys_tonnes: 100, energy_gw: 100, deuterium_kg: 50 },
    maintenance_cost_alloys: 5.0,
    description: "Générateur thermique lourd à confinement magnétique immunisé contre les tempêtes.",
  },
  SUPERCALCULATEUR_NIA: {
    blueprint_id: "SUPERCALCULATEUR_NIA",
    name: "Supercalculateur Quantique N.I.A.",
    category: "SEC",
    unlocked_era: 5,
    min_leader_level: 3,
    min_governance_level: 4,
    allowed_z_levels: ["Z_MINUS_2_DEEP", "Z_ZERO_DOME"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 3, height: 3 },
    base_inputs: { energy_gw: 50, water_l: 200 },
    base_outputs: { q_flops: 300, research_speed_pct: 35 },
    construction_cost: { alloys_tonnes: 80, energy_gw: 80 },
    maintenance_cost_alloys: 3.5,
    description: "Extension physique du réseau neuronal de bord pour calculs de prospective.",
  },
  POSTE_DEFENSE_PERIMETRE: {
    blueprint_id: "POSTE_DEFENSE_PERIMETRE",
    name: "Tourelle Défensive de Périmètre",
    category: "SEC",
    unlocked_era: 1,
    min_leader_level: 1,
    min_governance_level: 1,
    allowed_z_levels: ["Z_PLUS_1_SURFACE", "Z_ZERO_DOME"],
    allowed_zones: ["ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 1, height: 1 },
    base_inputs: { energy_gw: 10 },
    base_outputs: { defense_rating: 40 },
    construction_cost: { alloys_tonnes: 12, energy_gw: 5 },
    maintenance_cost_alloys: 0.6,
    description: "Canon plasma automatique repoussant la faune hostile et les débris orageux.",
  },
  FERME_AEROPONIQUE_INDUSTRIELLE: {
    blueprint_id: "FERME_AEROPONIQUE_INDUSTRIELLE",
    name: "Ferme Aéroponique Industrielle",
    category: "AGR",
    unlocked_era: 2,
    min_leader_level: 1,
    min_governance_level: 2,
    allowed_z_levels: ["Z_ZERO_DOME", "Z_MINUS_1_SUB"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 3, height: 2 },
    base_inputs: { water_l: 150, energy_gw: 20 },
    base_outputs: { biomass_kg: 450, oxygen_l: 200 },
    construction_cost: { alloys_tonnes: 28, energy_gw: 15 },
    maintenance_cost_alloys: 1.1,
    description: "Culture verticale sous brume nutritive optimisant la biomasse comestible.",
  },
  SAS_SPATIAL_AEROCOMMERCE: {
    blueprint_id: "SAS_SPATIAL_AEROCOMMERCE",
    name: "Terminal Logistique & Fret",
    category: "LOG",
    unlocked_era: 2,
    min_leader_level: 1,
    min_governance_level: 1,
    allowed_z_levels: ["Z_PLUS_1_SURFACE", "Z_PLUS_2_ORBIT"],
    allowed_zones: ["ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 3, height: 3 },
    base_inputs: { energy_gw: 25 },
    base_outputs: { trade_capacity: 100, storage_alloys: 200 },
    construction_cost: { alloys_tonnes: 35, energy_gw: 20 },
    maintenance_cost_alloys: 1.8,
    description: "Hangar de chargement pressurisé facilitant les échanges de minerai et conteneurs.",
  },
  LABORATOIRE_BIORECHERCHE: {
    blueprint_id: "LABORATOIRE_BIORECHERCHE",
    name: "Laboratoire de Biorecherche Quantique",
    category: "RES",
    unlocked_era: 3,
    min_leader_level: 2,
    min_governance_level: 2,
    allowed_z_levels: ["Z_ZERO_DOME", "Z_MINUS_1_SUB"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 2, height: 2 },
    base_inputs: { energy_gw: 30, oxygen_l: 100 },
    base_outputs: { research_speed_pct: 15, health_recovery_rate: 10 },
    construction_cost: { alloys_tonnes: 40, energy_gw: 30 },
    maintenance_cost_alloys: 2.0,
    description: "Séquenceur génétique analysant les micro-organismes d'exoplanètes.",
  },
  PALAIS_DECRETAL_SENAT: {
    blueprint_id: "PALAIS_DECRETAL_SENAT",
    name: "Agora & Palais Décrétal du Sénat",
    category: "GOV",
    unlocked_era: 3,
    min_leader_level: 2,
    min_governance_level: 3,
    allowed_z_levels: ["Z_ZERO_DOME"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 4, height: 3 },
    base_inputs: { energy_gw: 35 },
    base_outputs: { social_cohesion: 25, credits_cr: 100 },
    construction_cost: { alloys_tonnes: 60, energy_gw: 40 },
    maintenance_cost_alloys: 2.5,
    description: "Cœur politique de l'Arche où siègent les représentants de factions.",
  },
  ARCOLOGIE_HABITATION_STELLAIRE: {
    blueprint_id: "ARCOLOGIE_HABITATION_STELLAIRE",
    name: "Arcologie Mégastructure d'Habitation",
    category: "HAB",
    unlocked_era: 4,
    min_leader_level: 3,
    min_governance_level: 3,
    allowed_z_levels: ["Z_ZERO_DOME", "Z_PLUS_1_SURFACE"],
    allowed_zones: ["ZONE_1_DOME_CORE"],
    grid_footprint: { width: 4, height: 4 },
    base_inputs: { oxygen_l: 600, water_l: 800, energy_gw: 60 },
    base_outputs: { housing_capacity: 1200, social_cohesion: 20 },
    construction_cost: { alloys_tonnes: 120, energy_gw: 90 },
    maintenance_cost_alloys: 4.5,
    description: "Cité verticale autonome abritant des milliers de citoyens dans un confort biophilique.",
  },
  BOUCLIER_IONIQUE_ORBITAL: {
    blueprint_id: "BOUCLIER_IONIQUE_ORBITAL",
    name: "Générateur de Bouclier Ionique",
    category: "SEC",
    unlocked_era: 4,
    min_leader_level: 3,
    min_governance_level: 3,
    allowed_z_levels: ["Z_PLUS_2_ORBIT", "Z_PLUS_1_SURFACE"],
    allowed_zones: ["ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 3, height: 3 },
    base_inputs: { energy_gw: 120 },
    base_outputs: { defense_rating: 150, storm_mitigation_pct: 50 },
    construction_cost: { alloys_tonnes: 90, energy_gw: 80 },
    maintenance_cost_alloys: 4.0,
    description: "Champ de force magnétique défléchissant les radiations stellaires et tempêtes ioniques.",
  },
  FONDERIE_NANO_ALLIAGES: {
    blueprint_id: "FONDERIE_NANO_ALLIAGES",
    name: "Fonderie Moléculaire de Nano-Alliages",
    category: "IND",
    unlocked_era: 4,
    min_leader_level: 3,
    min_governance_level: 3,
    allowed_z_levels: ["Z_MINUS_1_SUB", "Z_MINUS_2_DEEP"],
    allowed_zones: ["ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 3, height: 3 },
    base_inputs: { energy_gw: 90 },
    base_outputs: { alloys_tonnes: 25 },
    construction_cost: { alloys_tonnes: 75, energy_gw: 60 },
    maintenance_cost_alloys: 3.0,
    description: "Complexe de synthèse atomique reconfigurant le régolithe en titane haute pureté.",
  },
  PORTE_DISCONTINUITE_SPATIALE: {
    blueprint_id: "PORTE_DISCONTINUITE_SPATIALE",
    name: "Porte de Discontinuité Spatiale",
    category: "LOG",
    unlocked_era: 5,
    min_leader_level: 3,
    min_governance_level: 4,
    allowed_z_levels: ["Z_PLUS_2_ORBIT"],
    allowed_zones: ["ZONE_3_HOSTILE_EXTERIOR"],
    grid_footprint: { width: 5, height: 5 },
    base_inputs: { energy_gw: 250, deuterium_kg: 25 },
    base_outputs: { interstellar_range_lightyears: 50, trade_capacity: 500 },
    construction_cost: { alloys_tonnes: 200, energy_gw: 200, deuterium_kg: 100 },
    maintenance_cost_alloys: 8.0,
    description: "Relais hyper-spatial plissant le continuum pour le saut de l'Arche vers la Seconde Terre.",
  },
};

// ==========================================
// 6. DÉCRETS DE DÉPART
// ==========================================

export const INITIAL_DECREES: Decree[] = [
  {
    id: "DEC-01",
    title: "Rationnement Énergétique des Dômes Tertiaires",
    category: "ECONOMIE",
    description: "Coupe l'éclairage récréatif et abaisse le chauffage pour économiser 25 GW.",
    philosophical_alignment: "CARTESIEN_AUTORITAIRE",
    active: false,
    costPerSol: {},
    effectsSummary: "+25 GW d'énergie · -5% de moral · Approbation Rationalistes +10%",
    factionSupport: { Rationalistes: 80, Biophiliques: -20, "Ingénieurs du Vide": 15 },
  },
  {
    id: "DEC-02",
    title: "Quotas de Biomasse pour les Serres",
    category: "BIEN_ETRE",
    description: "Alloue des suppléments hydriques aux serres pour stimuler la production vivrière.",
    philosophical_alignment: "EXISTENTIALISTE_DEMOCRATE",
    active: false,
    costPerSol: { water_l: 100 },
    effectsSummary: "+200 kg biomasse/Sol · +8% de moral · Approbation Biophiliques +25%",
    factionSupport: { Rationalistes: -10, Biophiliques: 90, "Ingénieurs du Vide": -10 },
  },
  {
    id: "DEC-03",
    title: "Heures Supplémentaires en Zone Hostile",
    category: "EXPANSION",
    description: "Augmente la rotation des équipes de forage extérieur en Zone 3.",
    philosophical_alignment: "CARTESIEN_AUTORITAIRE",
    active: false,
    costPerSol: {},
    effectsSummary: "+30% d'extraction d'alliages · +10% de fatigue colons · Risque d'avarie +15%",
    factionSupport: { Rationalistes: 20, Biophiliques: -30, "Ingénieurs du Vide": 75 },
  },
  {
    id: "DEC-04",
    title: "Autonomie Décentralisée des Holons",
    category: "ECONOMIE",
    description: "Autorise chaque dôme à gérer ses tampons de stockage en autarcie (Viable System Model).",
    philosophical_alignment: "STRUCTURALISTE_COLLECTIF",
    active: false,
    costPerSol: {},
    effectsSummary: "+100% de résilience en rupture de réseau · -10% de rendement centralisé",
    factionSupport: { Rationalistes: -15, Biophiliques: 20, "Ingénieurs du Vide": 25 },
  },
];

// ==========================================
// 7. CORPS CÉLESTES DU SYSTÈME 4X
// ==========================================

export const INITIAL_CELESTIAL_BODIES: CelestialBody[] = [
  {
    id: "STAR-CORE",
    name: "Étoile Primaire Alpha",
    type: "STAR",
    orbitRadius: 0.0,
    habitabilityScore: 0,
    scanned: true,
    minedOutPct: 0,
    resources: { energy_gw: 10000 },
    hazards: ["Tempêtes Plasmiques", "Radiations Gamma"],
    description: "Étoile centrale du système alimentant le flux de radiance stellaire.",
  },
  {
    id: "PLANET-TARGET",
    name: "Planète Colonisée (Site Arche)",
    type: "PLANET",
    orbitRadius: 1.2,
    habitabilityScore: 65,
    scanned: true,
    minedOutPct: 5,
    resources: { alloys_tonnes: 5000, water_l: 80000, biomass_kg: 20000 },
    outpostInstalled: true,
    hazards: ["Tempêtes de Silice", "Atmosphère Corrosive"],
    description: "Emplacement principal de l'atterrisseur et des dômes de l'Arche.",
  },
  {
    id: "MOON-KAELIS-A",
    name: "Lune Kaelis-Minima",
    type: "MOON",
    orbitRadius: 1.25,
    habitabilityScore: 18,
    scanned: false,
    minedOutPct: 0,
    resources: { deuterium_kg: 800, alloys_tonnes: 2000 },
    hazards: ["Vide Absolu", "Froid Cryogénique"],
    description: "Satellite stérile aux poches riches en deutérium et régolithe pur.",
  },
  {
    id: "ASTEROID-BELT-SIGMA",
    name: "Ceinture d'Astéroïdes d'Oort",
    type: "ASTEROID_BELT",
    orbitRadius: 2.8,
    habitabilityScore: 0,
    scanned: false,
    minedOutPct: 0,
    resources: { alloys_tonnes: 15000, deuterium_kg: 1200 },
    hazards: ["Impacts Cinétiques", "Micro-météorites"],
    description: "Champ d'astéroïdes denses propice au forage par laser orbital.",
  },
  {
    id: "ANOMALY-XENO-01",
    name: "Anomalie Monolithique Xéno-01",
    type: "RUIN",
    orbitRadius: 4.1,
    habitabilityScore: 5,
    scanned: false,
    minedOutPct: 0,
    resources: { q_compute: 500 },
    hazards: ["Distorsion Quantique"],
    description: "Structure précurseur émettant un signal mathématique cartésien non résolu.",
  },
];
